Hotfix/add new event callback
RidgeRun/gst-interpipe pull request #112
Opened 2022-01-13 16:33 UTC by jafet-chaves

resolves #107

2022-01-13 23:46 UTC, michaelgruner requested changes

2022-01-13 23:46 UTC, michaelgruner commented on gst/interpipe/gstinterpipesink.c
> +  callbacks.new_event = GST_DEBUG_FUNCPTR (gst_inter_pipe_sink_new_event);
We don't actually want to implement this callback. Let's set it to null so the base class knows it doesn't need to call anything. The reason it is attempting to invoke the callback is because the struct was likely initialized randomly and the pointer is non-null (making the base class think it contains a valid method). I recommend initializing the callback struct to zero, or memsetting it out. This way this won't happen again if GStreamer adds another callback.

2022-01-14 00:57 UTC, lleon95 requested changes

2022-01-14 00:57 UTC, lleon95 commented on gst/interpipe/gstinterpipesink.c
> +  memset (&callbacks, 0, sizeof (callbacks));
I think you can initialise it in the declaration:

```c
GstAppSinkCallbacks callbacks = {0};
```

2022-01-14 00:57 UTC, lleon95 commented on gst/interpipe/gstinterpipesink.c
> +#endif
Since you are setting the whole `callbacks` struct, you don't need to set it to `NULL` given that it is already NULL

2022-01-14 01:00 UTC, lleon95 commented
I think we can take advantage of it and fix the copyright year in the README:

```
GstInterpipe copyright (C) 2016 RidgeRun LLC
```

2022-01-14 14:33 UTC, jafet-chaves commented on gst/interpipe/gstinterpipesink.c
> +  memset (&callbacks, 0, sizeof (callbacks));
I think this just comes down to a matter of taste. I prefer the current implementation due to the alignment bytes also being set to zero in the case of memset.

2022-01-14 14:35 UTC, jafet-chaves commented on gst/interpipe/gstinterpipesink.c
> +#endif
You are right, this is redundant

2022-01-14 14:50 UTC, lleon95 approved these changes

2022-01-17 16:48 UTC, mleivaf approved these changes

2022-01-18 17:39 UTC, michaelgruner approved these changes

2022-01-18 17:53 UTC, merged