Test with common for 1.10
RidgeRun/gst-interpipe pull request #66
Opened 2020-09-21 18:37 UTC by jcaballeros

The latest GStreamer common version was causing a problem with gtkdoc-scan
in systems with GStreamer 1.8 and 1.10. To avoid this, we downgrade the
to the submodule common to the version for GStreamer 1.10.

2020-09-21 18:40 UTC, jcaballeros commented
The following error was showing on systems with GStreamer 1.8 and 1.10 when built with gtkdoc enabled:

```
gst-interpipe-scan.c: In function 'get_object_types':
gst-interpipe-scan.c:228:16: error: implicit declaration of function 'gst_tracer_factory_get_tracer_type' [-Werror=implicit-function-declaration]
         type = gst_tracer_factory_get_tracer_type (t);
                ^
gst-interpipe-scan.c:228:9: error: nested extern declaration of 'gst_tracer_factory_get_tracer_type' [-Werror=nested-externs]
         type = gst_tracer_factory_get_tracer_type (t);
         ^
cc1: all warnings being treated as errors
```

To work around this, we downgrade the common submodule version to 1.10, so that gst-interpipe can be built with gtk-doc enabled in older systems too.

2020-09-21 19:24 UTC, bill9889 requested changes
Could this downgrade break anything added recently?

2020-09-21 19:59 UTC, jcaballeros commented
> Could this downgrade break anything added recently?

It has been tested with GStreamer 1.16.

2020-09-21 20:04 UTC, bill9889 approved these changes

2020-09-22 20:41 UTC, edisonf approved these changes

2020-09-24 16:05 UTC, mmontero approved these changes

2020-09-24 17:45 UTC, merged